In [4]:
!pip install requests

Requirement already satisfied: requests in c:\users\dell\anaconda3\lib\site-packages (2.26.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from requests) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\dell\anaconda3\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\dell\anaconda3\lib\site-packages (from requests) (2.0.4)

In [ ]:
import pandas as pd
import numpy as np
import requests

In [12]:
import requests, zipfile, io

In [14]:
r = requests.get('http://200.152.38.155/CNPJ/K3241.K03200Y0.D20514.EMPRECSV.zip')
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall(r"C:\Users\DELL\Desktop\Python\Sefaz")

In [23]:
df = pd.read_csv('K3241.K03200Y0.D20514.EMPRE.CSV', sep=';', on_bad_lines='skip', encoding = 'latin-1', header=None)

In [24]:
df

,0,1,2,3,4,5,6
0,41273602,FABIO SOUZA DO ROSARIO 80392440210,2135,50,"15000,00",1.0,NaN
1,41273603,GRAFLINE ACESSORIOS GRAFICOS LTDA,2062,49,"10000,00",1.0,NaN
2,41273604,RUMO - ESTUDIO DE DANCA LTDA,2062,49,"10000,00",1.0,NaN
3,41273605,WALLACE DE OLIVEIRA SILVA 42992101826,2135,50,"1000,00",1.0,NaN
4,41273606,MARCOS CESAR DE MELO JUNIOR 02569327190,2135,50,"72000,00",1.0,NaN
...,...,...,...,...,...,...,...
9387784,98819550,ANTONIO ORIQUES CARDOSO,2135,50,"0,00",1.0,NaN
9387785,98819568,ELI ORIQUES CARDOSO,2135,50,"0,00",1.0,NaN
9387786,98819600,PAULINO LEMOS DA SILVA,2135,50,"0,00",5.0,NaN
9387787,98819832,JOAO FELTRIN,2135,50,"0,00",1.0,NaN
9387788,99017782,SOCIEDADE UNIAO DE ARTISTAS,3999,16,"0,00",5.0,NaN

In [34]:
df = df.rename(columns={0: 'CNPJ', 1: 'Razao_Social', 2: 'Natureza_Juridica', 3: 'Qualificacao', 4: 'Capital_Social', 5: 'Porte', 6: 'Ente_Federativo'})

In [35]:
df

,CNPJ,Razao_Social,Natureza_Juridica,Qualificacao,Capital_Social,Porte,Ente_Federativo
0,41273602,FABIO SOUZA DO ROSARIO 80392440210,2135,50,"15000,00",1.0,NaN
1,41273603,GRAFLINE ACESSORIOS GRAFICOS LTDA,2062,49,"10000,00",1.0,NaN
2,41273604,RUMO - ESTUDIO DE DANCA LTDA,2062,49,"10000,00",1.0,NaN
3,41273605,WALLACE DE OLIVEIRA SILVA 42992101826,2135,50,"1000,00",1.0,NaN
4,41273606,MARCOS CESAR DE MELO JUNIOR 02569327190,2135,50,"72000,00",1.0,NaN
...,...,...,...,...,...,...,...
9387784,98819550,ANTONIO ORIQUES CARDOSO,2135,50,"0,00",1.0,NaN
9387785,98819568,ELI ORIQUES CARDOSO,2135,50,"0,00",1.0,NaN
9387786,98819600,PAULINO LEMOS DA SILVA,2135,50,"0,00",5.0,NaN
9387787,98819832,JOAO FELTRIN,2135,50,"0,00",1.0,NaN
9387788,99017782,SOCIEDADE UNIAO DE ARTISTAS,3999,16,"0,00",5.0,NaN

In [37]:
df.Ente_Federativo.isnull().count()

9387789

# Estabelecimentos

In [ ]:
r = requests.get('http://200.152.38.155/CNPJ/K3241.K03200Y0.D20514.ESTABELE.zip')
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall(r"C:\Users\DELL\Desktop\Python\Sefaz")

In [ ]:
df_est1 = pd.read_csv('K3241.K03200Y0.D20514.ESTABELE.csv', sep=';', on_bad_lines='skip', encoding = 'latin-1', header=None)

In [ ]:
df_est1

In [ ]:
df_est1 = df_est1.rename(columns={0: 'CNPJ', 1: 'Razao_Social', 2: 'Natureza_Juridica', 3: 'Qualificacao', 4: 'Capital_Social', 5: 'Porte', 6: 'Ente_Federativo'})